name: "Build action: Foxy, Galactic, Humble, Rolling"

on:
  push:
    branches: [ rolling ]
  pull_request:
    branches: [ rolling ]
  schedule:
    # Run once per day to detect broken dependencies
    - cron: '13 6 * * *'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - ros_distribution: "foxy"
            os: "ubuntu-20.04"
          - ros_distribution: "galactic"
            os: "ubuntu-20.04"
          - ros_distribution: "humble"
            os: "ubuntu-22.04"
          - ros_distribution: "rolling"
            os: "ubuntu-22.04"
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: ros-tooling/setup-ros@v0.3
      with:
        required-ros-distributions: ${{ matrix.ros_distribution }}
    - uses : ros-tooling/action-ros-ci@v0.2
      with:
        package-name: fmilibrary_vendor
        vcs-repo-file-url: ""
        target-ros2-distro: ${{ matrix.ros_distribution }}
